# Generated by Django 5.1.3 on 2024-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=50)),
                ('hotelDescription', models.CharField(max_length=50)),
                ('bookingPrice', models.IntegerField()),
            ],
        ),
    ]
